# Practica de Algebra lineal

### *Nombre*

<span style="color:blue">Ejercicio 1:  
Usando los procedimientos add y mult_vector_escalar definidos anteriormente, calcular:   
{$\alpha$[1,2]+[3,4] : $\alpha$$\in$$\mathbb{R}$, 0$\leq$$\alpha$$\leq$1, con una precision de dos decimales (para la multiplicación)}</style>

In [1]:
def addn(v,w):
    return[v[i]+w[i] for i in range(len(v))]

In [19]:
def mult_vector_escalar(alpha,v):
    return [alpha*v[i] for i in range(len(v))]

In [3]:
def sum_y_mult_vector_escalar(alpha, v, w):
    return [addn(mult_vector_escalar(alpha, v), w)]

In [4]:
alpha=2
sum_y_mult_vector_escalar(alpha, [1,2], [3,4])

[[5, 8]]

<span style="color:blue">Ejercicio 2:  
Mortadelo y Filemón usan como clave el siguiente vector:</style>  
> <span style="color:blue">**k**=[0,1,0,0,1,0,1,0,1,0]</style>  

<span style="color:blue">Mortadelo quiere enviarle a Filemón el siguiente mensaje:</style>  
> <span style="color:blue">**p**=[0,0,0,1,1,1,0,1,0,1]</style>  

<span style="color:blue">Mortadelo encripta su mensaje añadiendo k:</style>  
> <span style="color:blue">**c**=**p**+**k**=[0,0,0,1,1,1,0,1,0,1]+[0,1,0,0,1,0,1,0,1,0]=[0,1,0,1,0,1,1,1,1,1]</style>  

<span style="color:blue">Cuando Filemón recibe el mensaje, lo desencripta añadiendo **k** a lo que ha recibido</style>  
> <span style="color:blue">**p**=**c**+**k**=[0,1,0,1,0,1,1,1,1,1]+[0,1,0,0,1,0,1,0,1,0]=[0,0,0,1,1,1,0,1,0,1]</style>    

<span style="color:blue">que es el mensaje original</style>    
  
 <span style="color:blue">¿Cómo lo harías en Python? (Definiendo un procedimiento)</style>  

In [5]:
def mensaje(recibido, clave, resultado):
    for i in range(len(recibido)):
        if recibido[i] == 0 and clave[i] == 0:
            resultado.append(0)            
        elif recibido[i] == 0 and clave[i] == 1:   
            resultado.append(1)            
        elif recibido[i] == 1 and clave[i] == 0:
            resultado.append(1)            
        elif recibido[i] == 1 and clave[i] == 1:
            resultado.append(0)            
    return resultado

In [6]:
resultado=[]
mensaje([0,1,0,1,0,1,1,1,1,1], [0,1,0,0,1,0,1,0,1,0], resultado)

[0, 0, 0, 1, 1, 1, 0, 1, 0, 1]

<span style="color:blue">Ejercicio 3: coste total o beneficio. </style>

<span style="color:blue">Supongamos que D es el conjunto de algunos ingredientes de la cerveza: </style>
> <span style="color:blue">D={lúpulo, malta, agua, levadura}</style>  

<span style="color:blue">Por otro lado tenemos el vector coste:</style>  
> <span style="color:blue">coste={lúpulo: 2,5€, malta: 1.5€, agua: 0.006€, levadura: 0,45€}</style>  

<span style="color:blue">Por último tenemos el vector cantidad con lo necesario para hacer una cerveza:</style>  
> <span style="color:blue">cantidad={lúpulo: 6u, malta: 14u, agua: 7u, levadura: 11u}</style>  

<span style="color:blue">¿Cuánto cuesta hacer una cerveza?</style> 

In [7]:
def producto_vectorial(u,v):
    return sum(u[i]*v[i] for i in range(len(u)))

In [8]:
round(producto_vectorial([2.5,1.5,0.006,0.45],[6,14,7,11]),2)

40.99

<span style="color:blue"> Ejercicio 4:   
¿Cómo escribirías cada uno de los vectores {[3,0,0],[0,2,0],[0,0,1]} como combinación lineal de {[2,0,1],[1,0,2],[2,2,2]}?
Escribe las combinaciones lineales en Python. Seguramente tenga que definir una nueva suma.</style>

In [18]:
[3, 0, 0] = 2 [2, 0, 1] − 1 [1, 0, 2] + 0 [2, 2, 2]

In [ ]:
[0, 2, 0] = -2/3[2, 0, 1] − 2/3[1, 0, 2] + 1 [2, 2, 2]

In [ ]:
[0, 0, 1] = -1/3[2, 0, 1] + 2/3[1, 0, 2] + 0 [2, 2, 2]

<span style="color:blue"> Ejercicio 5:  
Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   2 & -3 \\
   -4 & 6\\
  \end{array} } \right]
$ , $
  B=
  \left[ {\begin{array}{cc}
   8 & 4 \\
   5 & 5\\
  \end{array} } \right]
$
y $
  C=
  \left[ {\begin{array}{cc}
   5 & -2 \\
   3 & 1\\
  \end{array} } \right]
$, queremos verificar que AB=AC pero que B≠C.</style> 

In [9]:
import numpy as np

matrizA = np.matrix(
    [[2, -3],
     [-4, 6]]
)

matrizB = np.matrix(
    [[8, 4],
     [5, 5]]
)

matrizC = np.matrix(
    [[5, -2],
     [3, 1]]
)

matrizA * matrizB

matrix([[ 1, -7],
        [-2, 14]])

In [11]:
matrizA * matrizC

matrix([[ 1, -7],
        [-2, 14]])

<span style="color:blue"> Ejercicio 6 :  
Dadas la matriz $
  A=
  \left[ {\begin{array}{cc}
   3 & -6 \\
   -1 & 2\\
  \end{array} } \right]
$ , construye una matriz B de 2 × 2 tal que AB sea igual a la matriz cero. Las columnas de B no deben ser iguales entre sí y deben ser distintas de cero.
.</style> 

In [15]:
import numpy as np

matrizA = np.matrix(
    [[3, -6],
     [-1, 2]]
)

matrizB = np.matrix(
    [[2, 6],
     [1, 3]]
)
matrizA*matrizB

matrix([[0, 0],
        [0, 0]])

<span style="color:blue"> Ejercicio 7:  
Sarrus para el determinante de orden 3.  
¿Cómo lo haríamos en Python?</style>

In [23]:
def xsarrus(A):
    return A[0,0] * A[1,1] * A[2,2] + A[1,0] * A[2,1] * A[0,2] + A[2,0] * A[0,1] * A[1,2] - (A[0,2] * A[1,1] * A[2,0] + A[2,2] * A[1,0] * A[0,1] + A[0,0] * A[2,1] * A[1,2])

In [25]:
import numpy as np
A = np.matrix(
    [[1,-4,2],
     [-2,8,-9],
     [-1,7,0]]
)

xsarrus(A)

15

<span style="color:blue"> Ejercicio 8:  
Sabemos que hay un modo directo en Python para calcular los rangos. Calcula el número de soluciones de estos tres sistemas de ecuaciones empleándolo.</style> 

> <span style="color:blue">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:blue">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:blue">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [15]:
#COEFICIENTE RANGO 3
import numpy as np
A=([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
])
detA=np.linalg.matrix_rank(A)
round(detA)

3

In [20]:
#AMPLIADA RANGO 3
import numpy as np
AA=([
    [1,-2,1,0],
    [0,2,-8,8],
    [-4,5,9,-9]
])
detAA=np.linalg.matrix_rank(AA)
round(detAA)

3

> <span style="color:blue">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:blue">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:blue">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [16]:
#COEFICIENTES RANGO 2
import numpy as np
B=([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
])
detB=np.linalg.matrix_rank(B)
round(detB)

2

In [17]:
#AMPLIADA RANGO 3
import numpy as np
BB=([
    [0,1,-4,8],
    [2,-3,2,1],
    [5,-8,7,1]
])
detBB=np.linalg.matrix_rank(BB)
round(detBB)

3

> <span style="color:blue">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:blue">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:blue">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [18]:
#COEFICIENTES RANGO 2
import numpy as np
C=([
    [1,0,1],
    [2,3,1],
    [3,3,2]
])
detC=np.linalg.matrix_rank(C)
round(detC)

2

In [19]:
#AMPLIADA RANGO 2
import numpy as np
CC=([
    [1,0,1,2],
    [2,3,1,3],
    [3,3,2,5]
])
detCC=np.linalg.matrix_rank(CC)
round(detCC)

2

<span style="color:blue"> Ejercicio 9:  
Comprobar que r(x,y) para un ángulo $\theta$ es una función lineal.</style> 

<span style="color:blue"> Ejercicio 10:  
¿Cuál es la representación coordenada del vector v= [6, 3, 2, 5] en términos de los vectores [2, 2, 2, 3], [1, 0, −1, 0], [0, 1, 0, 1]?</style> 

In [6]:
import numpy as np

A = np.matrix([
    [2,1,0],
    [2,0,1],
    [2,-1,0],
    [3,0,1]
])
detA=np.linalg.matrix_rank(A)
round(detA)

AM = np.matrix([
    [2,1,0,6],
    [2,0,1,3],
    [2,-1,0,2],
    [3,0,1,5]
])
detAM=np.linalg.matrix_rank(AM)
round(detAM)
#Rango 3 para la matriz y su ampliada
C = np.matrix([
    [2,1,0],
    [2,0,1],
    [2,-1,0]
])
B = np.matrix(
    [[6],
     [3],
     [2]]
)
X = np.linalg.solve(C, B)
X

matrix([[ 2.],
        [ 2.],
        [-1.]])

<span style="color:blue"> Ejercicio 11:  
Supongamos que queremos diseñar la red de internet para el otro campus universitario.  
La red debe lograr la misma conectividad que el grafo de entrada.  
Una arista representa un posible cable.  
El peso de la arista es el coste de instalar el cable.  
Nuestro objetivo es minimizar el coste total, usando el algoritmo Grow y el algoritmo Shrink.  </style> 

#Grow

> <span style="color:orange"> S={{Pembroke Campus, Bio-Med},{Pembroke Campus, Atheletic Complex}} </style>

#Shrink

> <span style="color:orange"> S={{Pembroke Campus, Atheletic Complex},{Pembroke Campus, Bio-Med}} </style>

<span style="color:blue"> Ejercicio 12:  
Sea la matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 0  & 0 & 5 \\
   0 & 2  & 0 & 7 \\
   0 & 0  & 3 & 9 \\
  \end{array} } \right]
$. Calcular el rango por filas y por columnas usando Python.</style> 

In [1]:
import numpy as np
M=([
    [1,0,0,5],
    [0,2,0,7],
    [0,0,3,9]
])
rangoM=np.linalg.matrix_rank(M)
rangoM

3

In [2]:
import numpy as np
M=([
    [1,0,0,5],
    [0,2,0,7],
    [0,0,3,9]
])
MT=np.transpose(M)
rangoMT=np.linalg.matrix_rank(MT)
rangoMT

3

<span style="color:blue"> Ejercicio 13 (opcional):  
Crea un algoritmo que transforme una matriz cualquiera en GF(2) en una matriz escalonada.</style> 

<span style="color:blue"> Ejercicio 14:  
Modificar lo necesario en los algoritmos para que funcionen y calculen el problema de la casa en llamas.</style>